version: '3'

services: 
    app:
        container_name: 'ts_clean_main'
        build:
            context: './app'
            dockerfile: 'dockerfile.dev'
        volumes:
            - './app:/app'
            - 'ts_clean_node_modules:/app/node_modules'
        env_file: 
            - "./app/.dev.env"
        ports:
            - '8001:80'
    db:
        container_name: 'ts_clean_psql'
        image: 'postgres:13-alpine'
        # build:
        #     context: './db'
        #     dockerfile: 'dockerfile'
        env_file: 
            './app/.dev.env'
        volumes:
            - 'pg_data:/var/lib/postgresql/data'
        command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    redis:
        container_name: ts_clean_redis
        image: redis:6-alpine
        volumes: 
            - 'redis_data:/data'
    test_db:
        container_name: 'ts_clean_psql_test'
        build:
            context: './db'
            dockerfile: 'dockerfile'
        env_file: 
            './app/.dev.env'
        command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
        


volumes: 
    ts_clean_node_modules:
    pg_data:
    redis_data:
            