version: '3'

services: 
    app:
        container_name: 'main_app'
        build:
            context: './app'
            dockerfile: 'dockerfile.dev'
        volumes:
            - './app:/app'
            - 'ts_clean_node_modules:/app/node_modules'
        env_file: 
            - "./app/.dev.env"
        ports:
            - '8001:80'
    db:
        container_name: 'postgres_db'
        build:
            context: './db'
            dockerfile: 'dockerfile'
        env_file: 
            './app/.dev.env'
        volumes:
            - 'pg_data:/var/lib/postgresql/data'
        command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]

volumes: 
    ts_clean_node_modules:
    pg_data:
            